Add-Type -AssemblyName System.Drawing
$canvas = [System.Drawing.Bitmap]::new(1600,900)
$draw = [System.Drawing.Graphics]::FromImage($canvas)
$draw.SmoothingMode = 'AntiAlias'
$draw.TextRenderingHint = 'AntiAliasGridFit'
$draw.Clear([System.Drawing.Color]::FromArgb(15,31,55))
$white = [System.Drawing.SolidBrush]::new([System.Drawing.Color]::FromArgb(242,247,255))
$blue = [System.Drawing.SolidBrush]::new([System.Drawing.Color]::FromArgb(74,185,238))
$muted = [System.Drawing.SolidBrush]::new([System.Drawing.Color]::FromArgb(172,194,218))
$title = [System.Drawing.Font]::new('Segoe UI',58,[System.Drawing.FontStyle]::Bold)
$sub = [System.Drawing.Font]::new('Segoe UI',28)
$small = [System.Drawing.Font]::new('Segoe UI',20)
$draw.FillRectangle($blue,250,190,12,420)
$draw.DrawString('Windows 11',$title,$white,300,225)
$draw.DrawString('Установка и переустановка',$sub,$white,305,355)
$draw.DrawString('Флешка  /  Восстановление  /  Сброс',$sub,$muted,305,430)
$draw.DrawString('Сначала — резервная копия',$sub,$blue,305,540)
$draw.DrawString('ITПОТОК',$small,$muted,305,690)
$canvas.Save((Join-Path $PSScriptRoot 'install-windows-11-cover-20261002.png'),[System.Drawing.Imaging.ImageFormat]::Png)
$draw.Dispose(); $canvas.Dispose()
